name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build du projet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
            cd stayalive
            npm install
            npm run build
        env:
          CI: true

      - name: Archivage des fichiers de construction
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
        cd stayalive
        npm install

      - name: Run tests and generate coverage report
        run: |
        cd stayalive
        npm test -- --coverage --watchAll=false

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  deploy:
    name: Déploiement
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déploiement
        run: |
          git config --local user.email "matthieu.queru@epitech.eu"
          git config --local user.name "Matthieu33197"
          git checkout release
          git add .
          git commit -m "Deploy to release branch"
          git push origin release

  notification:
    name: Notification
    needs: [build, test, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Envoyer une notification en cas de succès
        if: ${{ success() }}
        run: echo "Le workflow a été exécuté avec succès. Toutes les étapes ont réussi."

      - name: Envoyer une notification en cas d'échec
        if: ${{ failure() }}
        run: echo "Le workflow a échoué. Veuillez vérifier les étapes précédentes pour plus d'informations."
